tasks for lesson 2
yathatguy/GoCourse pull request #2
Opened 2020-02-13 14:52 UTC by yathatguy

2020-02-15 10:22 UTC, shmel1k requested changes

2020-02-15 10:22 UTC, shmel1k commented on .idea/workspace.xml
> +  </component>
Вот это всё надо унести в .gitignore

2020-02-15 10:22 UTC, shmel1k commented on cmd/syntax_task2/fibonacci/main.go
> +	}
Вообще, здесь можно(и нужно) без массива обходиться
Тут хватит двух переменных -- это константная память
Когда появляется массив -- это уже O(N) дополнительной памяти

2020-02-15 10:22 UTC, shmel1k commented on cmd/syntax_task2/simpleNumbers/main.go
> +	}
Вообще, очень сложно
Зачем нужен дополнительный массив, который прилетает извне?
Можно просто передавать N до которого мы ищем. Ну или количество простых чисел, которое нам нужно
Можно сделать так
```go
func findSimple(n int) {
    foundCnt := 0
    isDividable := false
    for i := 2; foundCnt < n ;i++ {
          isDividable = false
          for j := 2; j < int(math.Sqrt(i)); j++ {
                if i % j == 0 {
                    isDividable = true
                    break
                }
          }
          if isDividable {
                foundCnt++
                fmt.Println(i)
          }
    }
}
```

2020-02-15 10:22 UTC, shmel1k commented on internal/numInput/main.go
> +		panic(nil)
Зачем панику? Присылать панику -- это не очень хорошо :)
Здесь подойдёт os.Exit(0)

2020-02-15 10:22 UTC, shmel1k commented on internal/numInput/main.go
> +		if err == nil {
В данном случае лучше написать так
```go
data := inputData(msg)
num, err := strconv.ParseInt(data, 10, 64)
if err != nil {
    log.Fatalf("unable to parse input: %s", err)
}

return int(num)
```

И можно вообще убрать внешний for, потому что здесь внутри всё равно Fatalln

2020-02-15 10:22 UTC, shmel1k commented on cmd/syntax_task2/simpleNumbers/main.go
> +	}
for i := 1; i <= l; i++ {
    resArr[i] = i
}

2020-02-25 17:28 UTC, yathatguy commented on .idea/workspace.xml
> +  </component>
завел себе `.gitignore` (сгенерил на gitignore.io), удалил лишние файлы
вообще я осознанно это оставлял в репозитории, чтоб конфигурация ide тоже сохранилась, чтоб не перенастраивать, если что то с ноутбуком произойдет или буду работать с другого)

2020-02-25 17:40 UTC, yathatguy commented on cmd/syntax_task2/fibonacci/main.go
> +	}
осознанно делал массив, чтоб можно было по необходимости обратиться к определенному элементу в последовательности. порой дают простые задания, а потом усложняют. я вот решил, что сохраню все  элементы в массиве.

переписал задание без использования массива.

2020-02-25 17:40 UTC, yathatguy commented on cmd/syntax_task2/fibonacci/main.go
> +	}
осознанно делал массив, чтоб можно было по необходимости обратиться к определенному элементу в последовательности. порой дают простые задания, а потом усложняют. я вот решил, что сохраню все  элементы в массиве.

переписал задание без использования массива.

2020-02-25 17:43 UTC, yathatguy commented on internal/numInput/main.go
> +		panic(nil)
согласен. поправил.

2020-02-25 18:01 UTC, yathatguy commented on cmd/syntax_task2/simpleNumbers/main.go
> +	}
как я понял, это улучшение читаемости кода, поправил.

2020-02-25 18:24 UTC, yathatguy commented on cmd/syntax_task2/simpleNumbers/main.go
> +	}
да, тут я не додумал. придумал простое решение и реализовал его.
были потом мысли про условие
```
for j := 2; j < int(math.Sqrt(i)); j++ {
                if i % j == 0 {
                    isDividable = true
                    break
                }
          }
```
но уже не стал этим заниматься. так конечно красивее.
ну и тут я тоже формировал массив, а не просто выводил на печать, чтоб иметь полный набор чисел и иметь возможность к ним обратиться.

код немного изменил и утащил к себе.

2020-02-27 10:12 UTC, merged